# Generated by Django 5.2.10 on 2026-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_houses', models.IntegerField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
