# Generated by Django 5.2.10 on 2026-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='ward',
            name='rate_per_house',
            field=models.FloatField(default=5),
        ),
    ]
